Painted walls with right colliders, scene placement (sth wrong with man asset)
error: 3sceneroom Stage2 doesnt work correctly because of MAN prefab (missing script)